### ISSUE TITLE
ECMWF sever

### ISSUE THREAD

**Issue by ctottrup** [DHI-GRAS/processing_SWAT#9]
https://github.com/DHI-GRAS/processing_SWAT/pull/7 does not fix download from new server. 

![image](https://cloud.githubusercontent.com/assets/6794617/16335802/fe6c8d1e-3a08-11e6-8dd3-e29d0a150380.png)

Is changes for e.g. GetECMWFClimateData.py not required?

**Comment by KittelC** [comment]
Yes, I made a pull request for that file as well, which should fix the error :)

**Comment by ctottrup** [comment]
Fixed with https://github.com/DHI-GRAS/processing_SWAT/pull/6
